apiVersion: v1
kind: Namespace
metadata:
  name: kubedump
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubedump
  name: kubedump
  namespace: kubedump
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view # adjust the clusterrole or create your own one when you need more permissions
subjects:
  - kind: ServiceAccount
    name: kubedump
    namespace: kubedump
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debian
  name: debian
  namespace: kubedump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      serviceAccountName: kubedump
      containers:
      - image: debian
        name: debian
        command:
          - sleep
          - infinity
