name: Go
on:
  push:
    paths:
      - go.mod
      - go.sum
      - "**.go"
      - ".github/workflows/go.yaml"
jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Format
        run: |
          go fmt ./...
          git diff --exit-code
      - name: Vet
        run: go vet ./...
      - uses: dominikh/staticcheck-action@v1.4.0
        with:
          install-go: false
      - name: Test
        run: go test -race ./...
