name: Go
on:
  push:
    paths:
      - go.mod
      - go.sum
      - "**.go"
      - ".github/workflows/go.yaml"
jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -race ./...
